"""CHanged the schema

Revision ID: 45cd20b122da
Revises: 0d315ddcc637
Create Date: 2021-02-26 13:21:55.443538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cd20b122da'
down_revision = '0d315ddcc637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanks', sa.Column('lat', sa.String(length=50), nullable=False))
    op.add_column('tanks', sa.Column('long', sa.String(length=50), nullable=False))
    op.drop_constraint('tanks_latitude_key', 'tanks', type_='unique')
    op.drop_constraint('tanks_longitude_key', 'tanks', type_='unique')
    op.create_unique_constraint(None, 'tanks', ['long'])
    op.create_unique_constraint(None, 'tanks', ['lat'])
    op.drop_column('tanks', 'latitude')
    op.drop_column('tanks', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanks', sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tanks', sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tanks', type_='unique')
    op.drop_constraint(None, 'tanks', type_='unique')
    op.create_unique_constraint('tanks_longitude_key', 'tanks', ['longitude'])
    op.create_unique_constraint('tanks_latitude_key', 'tanks', ['latitude'])
    op.drop_column('tanks', 'long')
    op.drop_column('tanks', 'lat')
    # ### end Alembic commands ###
